version: "3.9"
   
services:
  bot:
    build: .
    command: python code/main.py
    environment:
      - API_URL=http://milepogawedki.xyz:8000/api/
      - DSC_TOKEN=NzE4MDk2MjYyNzkyMjE2NTc2.Xtj5Qg.DZN_xs7NSHDQzb3ydurj-r_mRx4
      - GUILD_ID=436894631578566676
      - CHANNEL_ID=960443126881845288
    volumes:
      - .:/code
