version: "3.9"
   
services:
  bot:
    build: .
    command: python code/main.py
    environment:
      - API_URL=http://milepogawedki.xyz:8000/api/
      - DSC_TOKEN=https://discord.com/developers/applications/
    ports:
      - "8080:8080"
    volumes:
      - .:/code
